# -*- coding: utf-8 -*-
"""7_Cycle_GAN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aSgoogFM6hyu0lHrpA7f03xSxC26E6mK
"""

import torch
import torchvision
import torch.nn as nn
import torch.nn.functional as F
import torchvision.transforms as transforms


import os
import time
import pickle
import zipfile
import numpy as np
import urllib.request
from PIL import Image
from tqdm import tqdm
import matplotlib.pyplot as plt

# ------------------------------------------------------------
# 0) Hyperparameters / config
# ------------------------------------------------------------
# Define some params
APPLE2ORANGE_PATH = './Apple2Orange_data/'
DEVICE = 'cuda'  # 'cpu' or 'cuda'
OUTPUT_PATH = './work_dirs/Cycle_GAN_01'
CHECKPOINT_SAVE_EVERY = 10
LATENT_DIMS = 100
LR = 0.0002
WORKERS = 4
NETWORK_FEATURES = 64
EPOCH = 50
BATCH_SIZE = 4


# ------------------------------------------------------------
# 1) Download + unzip Apple2Orange dataset
# ------------------------------------------------------------
# download the dataset from https://efrosgans.eecs.berkeley.edu/cyclegan/datasets/apple2orange.zip in APPLE2ORANGE_PATH
os.makedirs(APPLE2ORANGE_PATH, exist_ok=True)
url = 'https://efrosgans.eecs.berkeley.edu/cyclegan/datasets/apple2orange.zip'
zip_path = os.path.join(APPLE2ORANGE_PATH, 'apple2orange.zip')
if not os.path.exists(zip_path):
    urllib.request.urlretrieve(url, zip_path)
    with zipfile.ZipFile(zip_path, 'r') as zip_ref:
        zip_ref.extractall(APPLE2ORANGE_PATH)
print('dataset prepare done!')


# ------------------------------------------------------------
# 2) Define a custom Dataset that returns (apple_img, orange_img)
# ------------------------------------------------------------
# CycleGAN uses *unpaired* image-to-image translation:
# - We do NOT need aligned (apple_i, orange_i) pairs.
# - Instead, during training we sample an apple image from domain A
#   and an orange image from domain B independently.
#
# This dataset class does exactly that by indexing with modulo:
# - apple index cycles through trainA images
# - orange index cycles through trainB images
# and the length is max(len(A), len(B)) so an epoch covers the larger domain.
class Apple2OrangeDataset(torch.utils.data.Dataset):
    def __init__(self, root_dir, transform=None, train_or_test='train'):
        """
        Args:
            root_dir (str): Path that contains the extracted 'apple2orange' folder.
            transform (callable): torchvision transforms applied to both domains.
            train_or_test (str): 'train' or 'test' to load the corresponding split.
        """
        # Domain A: apples, Domain B: oranges (following CycleGAN naming convention)
        self.apple_path = os.path.join(root_dir, f'apple2orange/{train_or_test}A')
        self.orange_path = os.path.join(root_dir, f'apple2orange/{train_or_test}B')
        self.transform = transform

        # List image filenames in each domain directory
        self.apple_images = sorted(os.listdir(self.apple_path))
        self.orange_images = sorted(os.listdir(self.orange_path))

        # Lengths of each domain
        self.apple_len = len(self.apple_images)
        self.orange_len = len(self.orange_images)

        # Define dataset length:
        self.length_dataset = max(self.apple_len, self.orange_len)

    def __len__(self):
        return self.length_dataset

    def __getitem__(self, index):
        """
        Returns:
            apple_array  (Tensor): one image from domain A (apples)
            orange_array (Tensor): one image from domain B (oranges)

        Note:
        - Images are unpaired: apple and orange returned here are not corresponding scenes.
        - Modulo (%) enables cycling through smaller domain without IndexError.
        """
        apple_image = self.apple_images[index % self.apple_len]
        orange_image = self.orange_images[index % self.orange_len]

        apple_image_path = os.path.join(self.apple_path, apple_image)
        orange_image_path = os.path.join(self.orange_path, orange_image)

        apple_array = Image.open(apple_image_path).convert("RGB")
        orange_array = Image.open(orange_image_path).convert("RGB")

        if self.transform:
            apple_array = self.transform(apple_array)
            orange_array = self.transform(orange_array)

        return apple_array, orange_array

# ------------------------------------------------------------
# 3) Preprocessing / augmentation transforms
# ------------------------------------------------------------
# Typical CycleGAN preprocessing for 256x256 images:
# - Resize: make the smaller side (or both sides, depending on PIL) 256
# - RandomCrop: add augmentation by taking random 256x256 patch (helps generalization)
# - ToTensor: convert to float tensor in [0,1]
# - Normalize: shift to roughly [-1,1] per channel, matching Tanh generator outputs
transform = transforms.Compose([
    transforms.Resize(256),
    transforms.RandomCrop(256),
    transforms.ToTensor(),
    transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))
])


# ------------------------------------------------------------
# 4) Build train/test datasets
# ------------------------------------------------------------
dataset = Apple2OrangeDataset(APPLE2ORANGE_PATH, transform=transform, train_or_test='train')
test_dataset = Apple2OrangeDataset(APPLE2ORANGE_PATH, transform=transform, train_or_test='test')

# ------------------------------------------------------------
# 5) DataLoader: batching + shuffling + I/O performance knobs
# ------------------------------------------------------------
dataloader = torch.utils.data.DataLoader(
    dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    num_workers=WORKERS,
    pin_memory=True,
    drop_last=True
)

# ------------------------------------------------------------
# 6) Output directories
# ------------------------------------------------------------
os.makedirs(os.path.join(OUTPUT_PATH, 'validated_imgs'), exist_ok=True)
os.makedirs(os.path.join(OUTPUT_PATH, 'checkpoints'), exist_ok=True)

# ------------------------------------------------------------
# CycleGAN-style building blocks (Generator + Patch Discriminator)
# ------------------------------------------------------------
# This code implements:
# 1) A PatchGAN discriminator: outputs a grid of probabilities (patch-level realism),
#    not a single scalar. This encourages high-frequency realism (texture/details).
# 2) A ResNet-based generator: encoder (downsample) -> residual blocks -> decoder (upsample).
#
# Important conventions here:
# - Input/output images are normalized to [-1, 1] (so generator ends with Tanh()).
# - InstanceNorm is used instead of BatchNorm (common in style transfer / CycleGAN)
#   because it is more stable for small batch sizes (often batch=1 in CycleGAN).
# - padding_mode='reflect' reduces edge artifacts compared to zero padding.
#
# NETWORK_FEATURES is a global hyperparameter (base channel count), e.g., 64.
# ------------------------------------------------------------


# ============================================================
# Discriminator blocks
# ============================================================

class DBlock(nn.Module):
    """
    One discriminator block: Conv -> (optional) InstanceNorm -> LeakyReLU.

    - Conv2d extracts features and (usually) downsamples when stride=2.
    - InstanceNorm2d normalizes per-sample (not across batch), stable for small batches.
    - LeakyReLU keeps gradients for negative activations (helps discriminator training).

    first_block=True skips InstanceNorm, which is a common PatchGAN design choice:
    the first layer often omits normalization to preserve raw signal statistics.
    """
    def __init__(self, in_channels, out_channels, first_block=False, **kwargs):
        super().__init__()
        self.block = nn.Sequential(
            # padding_mode='reflect' reduces border artifacts in image-to-image tasks
            nn.Conv2d(in_channels, out_channels, **kwargs, padding_mode='reflect', bias=True),

            # Skip normalization in the first layer (common practice)
            nn.InstanceNorm2d(out_channels) if not first_block else nn.Identity(),

            nn.LeakyReLU(0.2, inplace=True)
        )

    def forward(self, x):
        return self.block(x)


class Discriminator(nn.Module):
    """
    PatchGAN Discriminator:
    - Input: (B, 3, 256, 256)
    - Output: (B, 1, ~30, ~30) probability map
      Each element corresponds to a "patch" decision ("real" vs "fake") for a receptive field.
    """
    def __init__(self):
        super().__init__()

        # Feature extractor part (mostly downsampling)
        self.model = nn.Sequential(
            # (B, 3, 256, 256) -> (B, 64, 128, 128)
            DBlock(3, NETWORK_FEATURES, first_block=True, kernel_size=4, stride=2, padding=1),

            # (B, 64, 128, 128) -> (B, 128, 64, 64)
            DBlock(NETWORK_FEATURES*1, NETWORK_FEATURES*2, kernel_size=4, stride=2, padding=1),

            # (B, 128, 64, 64) -> (B, 256, 32, 32)
            DBlock(NETWORK_FEATURES*2, NETWORK_FEATURES*4, kernel_size=4, stride=2, padding=1),

            # stride=1 here: stop aggressive downsampling; increase receptive field while
            # keeping a reasonably dense patch grid.
            # (B, 256, 32, 32) -> (B, 512, 31, 31)
            DBlock(NETWORK_FEATURES*4, NETWORK_FEATURES*8, kernel_size=4, stride=1, padding=1),
        )

        # Final classifier head:
        # (B, 512, 31, 31) -> (B, 1, 30, 30)
        # Sigmoid maps to [0,1] probabilities.
        self.last_layer = nn.Sequential(
            nn.Conv2d(NETWORK_FEATURES*8, 1, kernel_size=4, stride=1, padding=1, padding_mode="reflect"),
            nn.Sigmoid()
        )

        # Teaching note:
        # If you use nn.BCEWithLogitsLoss, you should REMOVE Sigmoid and output logits instead,
        # which is numerically more stable.

    def forward(self, x):
        # Safety reshape: expects flattened input sometimes.
        x = x.view(-1, 3, 256, 256)

        x = self.model(x)        # patch feature maps
        x = self.last_layer(x)   # patch probabilities
        return x


# ============================================================
# Generator blocks
# ============================================================

class GBlock(nn.Module):
    """
    A generator block used for both downsampling and upsampling.

    down=True  -> Conv2d (usually stride=2) to reduce spatial size (encoder)
    down=False -> ConvTranspose2d to increase spatial size (decoder)

    InstanceNorm + ReLU is standard in CycleGAN generators.
    use_act=False is used in residual blocks' second conv to keep the residual path "linear-ish".
    """
    def __init__(self, in_channels, out_channels, down=True, use_act=True, **kwargs):
        super().__init__()
        self.conv = nn.Sequential(
            # Downsample: standard conv with reflect padding to avoid edge artifacts
            nn.Conv2d(in_channels, out_channels, **kwargs, padding_mode="reflect") if down else
            # Upsample: transposed conv (a learnable upsampling)
            nn.ConvTranspose2d(in_channels, out_channels, **kwargs),

            nn.InstanceNorm2d(out_channels),

            # Activation: ReLU for most layers; Identity in some places (e.g., residual tail)
            nn.ReLU(inplace=True) if use_act else nn.Identity()
        )

    def forward(self, x):
        return self.conv(x)


class ResidualBlock(nn.Module):
    """
    ResNet block: x -> Conv -> ReLU -> Conv -> +x

    Both convs keep spatial size fixed (kernel=3, stride=1, padding=1).
    """
    def __init__(self, channels):
        super().__init__()
        self.block = nn.Sequential(
            # First conv with activation
            GBlock(channels, channels, use_act=True, kernel_size=3, stride=1, padding=1),

            # Second conv without activation (so residual addition is not overly squashed)
            GBlock(channels, channels, use_act=False, kernel_size=3, stride=1, padding=1)
        )

    def forward(self, x):
        # Skip connection: preserves input information and stabilizes training
        return x + self.block(x)


class Generator(nn.Module):
    """
    CycleGAN Generator (ResNet-based):
      Input  (B, 3, 256, 256)
        -> initial 7x7 conv
        -> 2x downsampling (to 64x64)
        -> N residual blocks (default 9 for 256x256 images in the original CycleGAN paper)
        -> 2x upsampling (back to 256x256)
        -> final 7x7 conv + Tanh

    Output is in [-1, 1], matching Normalize(mean=0.5,std=0.5).
    """
    def __init__(self, num_residuals=9):
        super().__init__()

        # Initial feature extraction:
        # Large 7x7 kernel captures wider context early.
        # (B, 3, 256, 256) -> (B, 64, 256, 256)
        self.initial = nn.Sequential(
            nn.Conv2d(3, NETWORK_FEATURES, kernel_size=7, stride=1, padding=3, padding_mode="reflect"),
            nn.ReLU(inplace=True),
        )

        # Encoder / downsampling:
        # Each stride=2 halves H and W, doubles channels
        self.down_block = nn.Sequential(
            # (B, 64, 256, 256) -> (B, 128, 128, 128)
            GBlock(NETWORK_FEATURES*1, NETWORK_FEATURES*2, kernel_size=3, stride=2, padding=1),

            # (B, 128, 128, 128) -> (B, 256, 64, 64)
            GBlock(NETWORK_FEATURES*2, NETWORK_FEATURES*4, kernel_size=3, stride=2, padding=1),
        )

        # Transformer / bottleneck (ResNet blocks at 64x64 resolution)
        # 9 residual blocks is standard for 256x256 training (often 6 for 128x128).
        self.residual_block = nn.Sequential(
            *[ResidualBlock(NETWORK_FEATURES*4) for _ in range(num_residuals)]
        )

        # Decoder / upsampling:
        # Use ConvTranspose2d blocks to return to original resolution
        self.up_block = nn.Sequential(
            # (B, 256, 64, 64) -> (B, 128, 128, 128)
            GBlock(
                NETWORK_FEATURES*4, NETWORK_FEATURES*2,
                down=False, kernel_size=3, stride=2, padding=1, output_padding=1
            ),

            # (B, 128, 128, 128) -> (B, 64, 256, 256)
            GBlock(
                NETWORK_FEATURES*2, NETWORK_FEATURES*1,
                down=False, kernel_size=3, stride=2, padding=1, output_padding=1
            ),
        )

        # Final projection back to RGB image space:
        # Tanh constrains output to [-1, 1]
        self.last = nn.Sequential(
            nn.Conv2d(NETWORK_FEATURES, 3, kernel_size=7, stride=1, padding=3, padding_mode="reflect"),
            nn.Tanh()
        )

    def forward(self, x):
        x = self.initial(x)
        x = self.down_block(x)
        x = self.residual_block(x)
        x = self.up_block(x)
        x = self.last(x)
        return x


# ============================================================
# Weight initialization
# ============================================================

def weights_init(m):
    """
    Custom initialization function to apply with model.apply(weights_init).

    - Convs/Linears: Xavier (Glorot) uniform is a reasonable default.
    - BatchNorm: normal init for weights and zero bias.
    """
    classname = m.__class__.__name__
    if classname.find('Conv') != -1:
        nn.init.xavier_uniform_(m.weight.data)
    elif classname.find('BatchNorm') != -1:
        nn.init.normal_(m.weight.data, 1.0, 0.02)
        nn.init.constant_(m.bias.data, 0)
    elif classname.find('Linear') != -1:
        nn.init.xavier_uniform_(m.weight.data)
        nn.init.constant_(m.bias.data, 0)

print('define the discriminator and generator')

# ------------------------------------------------------------
# 7) Instantiate models (CycleGAN has 2 generators + 2 discriminators)
# ------------------------------------------------------------
# CycleGAN learns *bidirectional* translation between two domains:
#   Domain A (apples)  <-->  Domain B (oranges)
#
# Generators:
#   gen_O : A -> B  (given an apple image, generate an orange-like image)
#   gen_A : B -> A  (given an orange image, generate an apple-like image)
#
# Discriminators (PatchGAN):
#   disc_A : judges whether an image looks like a real apple-domain image
#   disc_O : judges whether an image looks like a real orange-domain image
disc_A = Discriminator().to(DEVICE)  # Classify apple-domain images as real or fake
disc_O = Discriminator().to(DEVICE)  # Classify orange-domain images as real or fake
gen_A  = Generator().to(DEVICE)      # Generator for mapping B -> A
gen_O  = Generator().to(DEVICE)      # Generator for mapping A -> B


# ------------------------------------------------------------
# 8) Weight initialization
# ------------------------------------------------------------
# Apply our custom init to all layers in each network.
# This can reduce training instability, especially for GANs.
disc_A.apply(weights_init)
disc_O.apply(weights_init)
gen_A.apply(weights_init)
gen_O.apply(weights_init)


# ------------------------------------------------------------
# 9) Optimizers
# ------------------------------------------------------------
# CycleGAN commonly uses Adam with betas=(0.5, 0.999) (GAN-standard choice).
# We use:
# - one optimizer for BOTH generators (gen_A + gen_O)
# - one optimizer for BOTH discriminators (disc_A + disc_O)
#
# This is convenient because the generator losses are coupled (cycle + identity).
gen_optimizer  = torch.optim.Adam(
    list(gen_A.parameters()) + list(gen_O.parameters()),
    lr=LR,
    betas=(0.5, 0.999)
)
disc_optimizer = torch.optim.Adam(
    list(disc_A.parameters()) + list(disc_O.parameters()),
    lr=LR,
    betas=(0.5, 0.999)
)


# ------------------------------------------------------------
# 10) Loss logging for plotting (per iteration)
# ------------------------------------------------------------
loss_log = {
    'time': [],   # wall-clock time per iteration (for speed profiling)
    'd_loss': [], # discriminator loss values
    'g_loss': []  # generator loss values
}


# ------------------------------------------------------------
# 11) Training loop
# ------------------------------------------------------------
# We alternate updates:
#   (1) update discriminators to better distinguish real vs fake
#   (2) update generators to fool discriminators + satisfy cycle/identity constraints
#
# Important: this implementation uses least-squares GAN loss (LSGAN):
# - discriminator uses MSE to targets 1 (real) and 0 (fake)
# - generator uses MSE to target 1 (want discriminator to say "real")
# This matches the original CycleGAN paper (often more stable than BCE).
for epoch in range(EPOCH):

    # Put networks in training mode:
    # - enables dropout (if any) and sets norms to training behavior
    disc_A.train()
    disc_O.train()
    gen_A.train()
    gen_O.train()

    loop = tqdm(dataloader, total=len(dataloader))
    loop.set_description(f'Epoch [{epoch + 1}/{EPOCH}]')

    # --------------------------------------------------------
    # Learning rate schedule: linear decay after halfway point
    # --------------------------------------------------------
    # CycleGAN typically keeps LR constant for first half of training,
    # then linearly decays to 0 in the second half.
    if epoch >= EPOCH / 2:
        decay = (EPOCH - epoch) / (EPOCH / 2)   # goes from 1 -> 0
        gen_optimizer.param_groups[0]['lr']  = LR * decay
        disc_optimizer.param_groups[0]['lr'] = LR * decay

    for i, data in enumerate(loop):
        start_time = time.time()

        # Each batch returns unpaired samples:
        # real_apple  from domain A, shape (B, 3, 256, 256)
        # real_orange from domain B, shape (B, 3, 256, 256)
        real_apple  = data[0].to(DEVICE)
        real_orange = data[1].to(DEVICE)

        # ====================================================
        # (A) Discriminator update
        # ====================================================
        # Generate fake images:
        # - fake_apple: B -> A  (turn oranges into apple-like)
        # - fake_orange: A -> B (turn apples into orange-like)
        #
        # detach() is critical when training discriminators:
        # - it stops gradients from flowing into the generators
        # - otherwise you'd accidentally update generators during D step
        fake_apple  = gen_A(real_orange)
        fake_orange = gen_O(real_apple)

        # --- Discriminator A (apple-domain) ---
        real_A_preds = disc_A(real_apple)           # should be close to 1
        fake_A_preds = disc_A(fake_apple.detach())  # should be close to 0

        # LSGAN losses (MSE):
        D_real_A_loss = F.mse_loss(real_A_preds, torch.ones_like(real_A_preds))
        D_fake_A_loss = F.mse_loss(fake_A_preds, torch.zeros_like(fake_A_preds))
        D_A_loss = D_real_A_loss + D_fake_A_loss

        # --- Discriminator O (orange-domain) ---
        real_O_preds = disc_O(real_orange)            # should be close to 1
        fake_O_preds = disc_O(fake_orange.detach())   # should be close to 0

        D_real_O_loss = F.mse_loss(real_O_preds, torch.ones_like(real_O_preds))
        D_fake_O_loss = F.mse_loss(fake_O_preds, torch.zeros_like(fake_O_preds))
        D_O_loss = D_real_O_loss + D_fake_O_loss

        # Average the two discriminator losses (optional scaling)
        D_loss = (D_A_loss + D_O_loss) / 2

        disc_optimizer.zero_grad()
        D_loss.backward()
        disc_optimizer.step()


        # ====================================================
        # (B) Generator update
        # ====================================================
        # GAN loss for generators:
        # - want discriminators to classify generated images as "real" (target=1)
        fake_A_preds = disc_A(fake_apple)   # now WITHOUT detach so gradients flow to gen_A
        fake_O_preds = disc_O(fake_orange)  # gradients flow to gen_O

        G_A_loss = F.mse_loss(fake_A_preds, torch.ones_like(fake_A_preds))
        G_O_loss = F.mse_loss(fake_O_preds, torch.ones_like(fake_O_preds))

        # ---------------------
        # Cycle-consistency loss
        # ---------------------
        # Enforce that translating there-and-back reconstructs the original:
        #   A -> B -> A ≈ A
        #   B -> A -> B ≈ B
        #
        # L1 is typically used (less blurring than L2).
        cycle_orange = gen_O(fake_apple)   # B->A->B reconstruction
        cycle_apple  = gen_A(fake_orange)  # A->B->A reconstruction

        consistency_A_loss = F.l1_loss(cycle_apple,  real_apple)
        consistency_O_loss = F.l1_loss(cycle_orange, real_orange)

        # -------------
        # Identity loss
        # -------------
        # Encourage generators to be near-identity when input is already in target domain:
        #   gen_A(A) ≈ A and gen_O(B) ≈ B
        #
        # This helps preserve color composition and prevents unnecessary changes.
        identity_A = gen_A(real_apple)
        identity_O = gen_O(real_orange)

        identity_A_loss = F.l1_loss(identity_A, real_apple)
        identity_O_loss = F.l1_loss(identity_O, real_orange)

        # Combine losses with standard CycleGAN weights:
        # - cycle loss weight often = 10
        # - identity loss weight often = 5 (sometimes 0.5*lambda_cycle in papers)
        G_loss = (
            G_A_loss + G_O_loss
            + (consistency_A_loss + consistency_O_loss) * 10.0
            + (identity_A_loss + identity_O_loss) * 5.0
        )

        gen_optimizer.zero_grad()
        G_loss.backward()
        gen_optimizer.step()


        # ====================================================
        # (C) Logging + tqdm display
        # ====================================================
        loss_log['d_loss'].append(D_loss.item())
        loss_log['g_loss'].append(G_loss.item())
        loss_log['time'].append(time.time() - start_time)

        loop.set_postfix(d_loss=D_loss.item(), g_loss=G_loss.item())


    # --------------------------------------------------------
    # 12) Save sample validation images every epoch
    # --------------------------------------------------------
    # We periodically translate a few fixed test images to monitor progress.
    # The saved grid is: [real_A | fake_O | real_O | fake_A] for several chosen examples.
    if (epoch + 1) % 1 == 0:
        with torch.no_grad():

            # Hand-picked indices for qualitative tracking across epochs
            # Each tuple selects (apple_index, orange_index) from the test split.
            eval_image_list = [(15, 13), (39, 39), (153, 156), (170, 233)]
            all_grids = []

            for i in range(len(eval_image_list)):
                # test_dataset returns (apple, orange) but we intentionally mix indices here
                # to keep domains unpaired even in visualization.
                real_A = test_dataset[eval_image_list[i][0]][0]
                real_O = test_dataset[eval_image_list[i][1]][1]

                # Add batch dimension: (C,H,W) -> (1,C,H,W)
                real_A = real_A[None].to(DEVICE)
                real_O = real_O[None].to(DEVICE)

                # Translate:
                # - fake_O: apple -> orange
                # - fake_A: orange -> apple
                fake_O = gen_O(real_A)
                fake_A = gen_A(real_O)

                # Convert from normalized torch tensors to numpy images in [0,1]
                # Because training normalized to [-1,1], undo by: (x + 1) / 2
                real_A = (real_A[0].cpu().numpy() + 1) / 2
                fake_O = (fake_O[0].cpu().numpy() + 1) / 2
                real_O = (real_O[0].cpu().numpy() + 1) / 2
                fake_A = (fake_A[0].cpu().numpy() + 1) / 2

                # Build a horizontal strip: [real_A | fake_O | real_O | fake_A]
                # axis=2 concatenates along width because tensors are (C, H, W)
                grid = np.concatenate([real_A, fake_O, real_O, fake_A], axis=2)

                # Convert (C,H,W) -> (H,W,C) for saving as an image
                grid = np.transpose(grid, (1, 2, 0))
                all_grids.append(grid)

            # Stack strips vertically to form a final grid image
            final_grid = np.vstack(all_grids)

            # Save as PNG:
            # - scale [0,1] -> [0,255]
            # - uint8 required for PIL image saving
            final_grid_img = Image.fromarray((final_grid * 255).astype(np.uint8))
            final_grid_img.save(os.path.join(OUTPUT_PATH, f"validated_imgs/epoch_{epoch+1}.png"))


    # --------------------------------------------------------
    # 13) Save loss log every epoch
    # --------------------------------------------------------
    # Pickle is convenient for quick reload, but not ideal for long-term portability.
    with open(os.path.join(OUTPUT_PATH, 'loss_log.pkl'), 'wb') as f:
        pickle.dump(loss_log, f)


    # --------------------------------------------------------
    # 14) Save model checkpoints periodically
    # --------------------------------------------------------
    # Saving state_dict() stores parameters only (standard PyTorch approach).
    # If you want resume training exactly, also save optimizers and current epoch.
    if (epoch + 1) % CHECKPOINT_SAVE_EVERY == 0 or epoch == EPOCH - 1:
        torch.save(gen_A.state_dict(),  os.path.join(OUTPUT_PATH, f'checkpoints/gen_A_epoch_{epoch+1:02d}.pth'))
        torch.save(gen_O.state_dict(),  os.path.join(OUTPUT_PATH, f'checkpoints/gen_O_epoch_{epoch+1:02d}.pth'))
        torch.save(disc_A.state_dict(), os.path.join(OUTPUT_PATH, f'checkpoints/disc_A_epoch_{epoch+1:02d}.pth'))
        torch.save(disc_O.state_dict(), os.path.join(OUTPUT_PATH, f'checkpoints/disc_O_epoch_{epoch+1:02d}.pth'))


# ------------------------------------------------------------
# 15) Plot and save loss curves
# ------------------------------------------------------------
# Two plots:
# (1) loss vs iteration (training dynamics)
# (2) loss vs wall-clock time (performance/profiling)
plt.style.use('ggplot')
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 5))

# Plot loss vs iterations (each appended value corresponds to one training iteration)
ax1.plot(loss_log['d_loss'], label='Discriminator Loss')
ax1.plot(loss_log['g_loss'], label='Generator Loss')
ax1.set_xlabel('Iteration')
ax1.set_ylabel('Loss')
ax1.set_title('Loss vs Iterations')
ax1.legend()

# Plot loss vs time (cumulative time on x-axis)
time_coords = np.cumsum(loss_log['time'])
ax2.plot(time_coords, loss_log['d_loss'], label='Discriminator Loss')
ax2.plot(time_coords, loss_log['g_loss'], label='Generator Loss')
ax2.set_xlabel('Time (seconds)')
ax2.set_ylabel('Loss')
ax2.set_title('Loss vs Time')
ax2.legend()

plt.tight_layout()
plt.savefig(os.path.join(OUTPUT_PATH, 'loss_curves.png'))
plt.close()