# -*- coding: utf-8 -*-
"""CS424 Test_function_group_project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pOHyW4IejmUg-uMXcNwu7uWLWrSYyrOU

## 1. Import the dependencies
"""

import os
import torch
import torch.nn as nn
import torch_fidelity
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import itertools
import random

from torch.utils.data import Dataset, DataLoader
from PIL import Image
import torchvision.transforms as transforms

seed = 42
torch.manual_seed(seed)
torch.cuda.manual_seed_all(seed)
np.random.seed(seed)
random.seed(seed)

torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

data_dir = "C:/Users/dan_t/OneDrive/Desktop/CS424"
if platform.system() != "Windows":
    data_dir = "/common/home/users/d/daniel.tan.2023/scratchDirectory"

"""## 2. Define your model"""

"""
Step 1. Define Generator
"""
# ============================================================
# Generator blocks
# ============================================================
NETWORK_FEATURES = 64

class GBlock(nn.Module):
    """
    A generator block used for both downsampling and upsampling.

    down=True  -> Conv2d (usually stride=2) to reduce spatial size (encoder)
    down=False -> ConvTranspose2d to increase spatial size (decoder)

    InstanceNorm + ReLU is standard in CycleGAN generators.
    use_act=False is used in residual blocks' second conv to keep the residual path "linear-ish".
    """
    def __init__(self, in_channels, out_channels, down=True, use_act=True, **kwargs):
        super().__init__()
        self.conv = nn.Sequential(
            # Downsample: standard conv with reflect padding to avoid edge artifacts
            nn.Conv2d(in_channels, out_channels, **kwargs, padding_mode="reflect") if down else
            # Upsample: transposed conv (a learnable upsampling)
            nn.ConvTranspose2d(in_channels, out_channels, **kwargs),

            nn.InstanceNorm2d(out_channels),

            # Activation: ReLU for most layers; Identity in some places (e.g., residual tail)
            nn.ReLU(inplace=True) if use_act else nn.Identity()
        )

    def forward(self, x):
        return self.conv(x)


class ResidualBlock(nn.Module):
    """
    ResNet block: x -> Conv -> ReLU -> Conv -> +x

    Both convs keep spatial size fixed (kernel=3, stride=1, padding=1).
    """
    def __init__(self, channels):
        super().__init__()
        self.block = nn.Sequential(
            # First conv with activation
            GBlock(channels, channels, use_act=True, kernel_size=3, stride=1, padding=1),

            # Second conv without activation (so residual addition is not overly squashed)
            GBlock(channels, channels, use_act=False, kernel_size=3, stride=1, padding=1)
        )

    def forward(self, x):
        # Skip connection: preserves input information and stabilizes training
        return x + self.block(x)


class Generator(nn.Module):
    """
    CycleGAN Generator (ResNet-based):
      Input  (B, 3, 256, 256)
        -> initial 7x7 conv
        -> 2x downsampling (to 64x64)
        -> N residual blocks (default 9 for 256x256 images in the original CycleGAN paper)
        -> 2x upsampling (back to 256x256)
        -> final 7x7 conv + Tanh

    Output is in [-1, 1], matching Normalize(mean=0.5,std=0.5).
    """
    def __init__(self, img_channels=3, num_residuals=9):
        super().__init__()

        # Initial feature extraction:
        # Large 7x7 kernel captures wider context early.
        # (B, 3, 256, 256) -> (B, 64, 256, 256)
        self.initial = nn.Sequential(
            nn.Conv2d(img_channels, NETWORK_FEATURES, kernel_size=7, stride=1, padding=3, padding_mode="reflect"),
            nn.ReLU(inplace=True),
        )

        # Encoder / downsampling:
        # Each stride=2 halves H and W, doubles channels
        self.down_block = nn.Sequential(
            # (B, 64, 256, 256) -> (B, 128, 128, 128)
            GBlock(NETWORK_FEATURES*1, NETWORK_FEATURES*2, kernel_size=3, stride=2, padding=1),

            # (B, 128, 128, 128) -> (B, 256, 64, 64)
            GBlock(NETWORK_FEATURES*2, NETWORK_FEATURES*4, kernel_size=3, stride=2, padding=1),
        )

        # Transformer / bottleneck (ResNet blocks at 64x64 resolution)
        # 9 residual blocks is standard for 256x256 training (often 6 for 128x128).
        self.residual_block = nn.Sequential(
            *[ResidualBlock(NETWORK_FEATURES*4) for _ in range(num_residuals)]
        )

        # Decoder / upsampling:
        # Use ConvTranspose2d blocks to return to original resolution
        self.up_block = nn.Sequential(
            # (B, 256, 64, 64) -> (B, 128, 128, 128)
            GBlock(
                NETWORK_FEATURES*4, NETWORK_FEATURES*2,
                down=False, kernel_size=3, stride=2, padding=1, output_padding=1
            ),

            # (B, 128, 128, 128) -> (B, 64, 256, 256)
            GBlock(
                NETWORK_FEATURES*2, NETWORK_FEATURES*1,
                down=False, kernel_size=3, stride=2, padding=1, output_padding=1
            ),
        )

        # Final projection back to RGB image space:
        # Tanh constrains output to [-1, 1]
        self.last = nn.Sequential(
            nn.Conv2d(NETWORK_FEATURES, img_channels, kernel_size=7, stride=1, padding=3, padding_mode="reflect"),
            nn.Tanh()
        )

    def forward(self, x):
        x = self.initial(x)
        x = self.down_block(x)
        x = self.residual_block(x)
        x = self.up_block(x)
        x = self.last(x)
        return x

"""
Step 2. Define Discriminator
"""
# ============================================================
# Discriminator blocks
# ============================================================

class DBlock(nn.Module):
    """
    One discriminator block: Conv -> (optional) InstanceNorm -> LeakyReLU.

    - Conv2d extracts features and (usually) downsamples when stride=2.
    - InstanceNorm2d normalizes per-sample (not across batch), stable for small batches.
    - LeakyReLU keeps gradients for negative activations (helps discriminator training).

    first_block=True skips InstanceNorm, which is a common PatchGAN design choice:
    the first layer often omits normalization to preserve raw signal statistics.
    """
    def __init__(self, in_channels, out_channels, first_block=False, **kwargs):
        super().__init__()
        self.block = nn.Sequential(
            # padding_mode='reflect' reduces border artifacts in image-to-image tasks
            nn.Conv2d(in_channels, out_channels, **kwargs, padding_mode='reflect', bias=True),

            # Skip normalization in the first layer (common practice)
            nn.InstanceNorm2d(out_channels) if not first_block else nn.Identity(),

            nn.LeakyReLU(0.2, inplace=True)
        )

    def forward(self, x):
        return self.block(x)


class Discriminator(nn.Module):
    """
    PatchGAN Discriminator:
    - Input: (B, 3, 256, 256)
    - Output: (B, 1, ~30, ~30) probability map
      Each element corresponds to a "patch" decision ("real" vs "fake") for a receptive field.
    """
    def __init__(self, img_channels=3):
        super().__init__()
        self.scale_factor = 8

        # Feature extractor part (mostly downsampling)
        self.model = nn.Sequential(
            # (B, 3, 256, 256) -> (B, 64, 128, 128)
            DBlock(img_channels, NETWORK_FEATURES, first_block=True, kernel_size=4, stride=2, padding=1),

            # (B, 64, 128, 128) -> (B, 128, 64, 64)
            DBlock(NETWORK_FEATURES*1, NETWORK_FEATURES*2, kernel_size=4, stride=2, padding=1),

            # (B, 128, 64, 64) -> (B, 256, 32, 32)
            DBlock(NETWORK_FEATURES*2, NETWORK_FEATURES*4, kernel_size=4, stride=2, padding=1),

            # stride=1 here: stop aggressive downsampling; increase receptive field while
            # keeping a reasonably dense patch grid.
            # (B, 256, 32, 32) -> (B, 512, 31, 31)
            DBlock(NETWORK_FEATURES*4, NETWORK_FEATURES*8, kernel_size=4, stride=1, padding=1),
        )

        # Final classifier head:
        # (B, 512, 31, 31) -> (B, 1, 30, 30)
        # Sigmoid maps to [0,1] probabilities.
        self.last_layer = nn.Sequential(
            nn.Conv2d(NETWORK_FEATURES*8, 1, kernel_size=4, stride=1, padding=1, padding_mode="reflect"),
            nn.Sigmoid()
        )

        # Teaching note:
        # If you use nn.BCEWithLogitsLoss, you should REMOVE Sigmoid and output logits instead,
        # which is numerically more stable.

    def forward(self, x):
        x = self.model(x)        # patch feature maps
        x = self.last_layer(x)   # patch probabilities
        return x


"""## 3. Load the data"""

"""
Step 6. DataLoader
"""
class ImageDataset(Dataset):
    def __init__(self, data_dir, mode='train', transforms=None):
        A_dir = os.path.join(data_dir, 'VAE_generation/train') # modification forbidden
        B_dir = os.path.join(data_dir, 'VAE_generation1/train')  # modification forbidden

        if mode == 'train':
            self.files_A = [os.path.join(A_dir, name) for name in sorted(os.listdir(A_dir))[:200]] # can be modified
            self.files_B = [os.path.join(B_dir, name) for name in sorted(os.listdir(B_dir))[:200]] # can be modified
        elif mode == 'valid':
            self.files_A = [os.path.join(A_dir, name) for name in sorted(os.listdir(A_dir))[200:250]] # can be modified
            self.files_B = [os.path.join(B_dir, name) for name in sorted(os.listdir(B_dir))[200:250]] # can be modified

        self.transforms = transforms

    def __len__(self):
        return len(self.files_A)

    def __getitem__(self, index):
        file_A = self.files_A[index]
        file_B = self.files_B[index]

        img_A = Image.open(file_A)
        img_B = Image.open(file_B)

        if self.transforms is not None:
            img_A = self.transforms(img_A)
            img_B = self.transforms(img_B)

        return img_A, img_B

"""## 4. Train your **model**"""

"""
Step 7. Training
"""
def main():
    """
    Step 3. Define Loss
    """
    criterion_GAN = nn.BCELoss()
    criterion_cycle = nn.L1Loss()
    criterion_identity = nn.L1Loss()

    """
    Step 4. Initalize G and D¶
    """
    G_AB = Generator(3)
    D_B = Discriminator(3)
    G_BA = Generator(3)
    D_A = Discriminator(3)

    ## Total parameters in CycleGAN should be less than 60M
    total_params = sum(p.numel() for p in G_AB.parameters()) + \
                sum(p.numel() for p in G_BA.parameters()) + \
                sum(p.numel() for p in D_A.parameters()) + \
                sum(p.numel() for p in D_B.parameters())


    """
    # modification of parameters computation is forbidden
    """
    total_params_million = total_params / (1024 * 1024)
    print(f'Total parameters in CycleGAN model: {total_params_million:.2f} million')

    cuda = torch.cuda.is_available()
    print(f'cuda: {cuda}')
    if cuda:
        G_AB = G_AB.cuda()
        D_B = D_B.cuda()
        G_BA = G_BA.cuda()
        D_A = D_A.cuda()
        criterion_GAN = criterion_GAN.cuda()
        criterion_cycle = criterion_cycle.cuda()
        criterion_identity = criterion_identity.cuda()

    """
    Step 5. Configure Optimizers
    """
    lr = 0.0002
    optimizer_G = torch.optim.Adam(itertools.chain(G_AB.parameters(), G_BA.parameters()), lr=lr)
    optimizer_D_A = torch.optim.Adam(D_A.parameters(), lr=lr)
    optimizer_D_B = torch.optim.Adam(D_B.parameters(), lr=lr)
    
    # Dynamically set model_dir based on the script's filename (without extension)
    script_name = os.path.splitext(os.path.basename(__file__))[0]
    model_dir = os.path.join(data_dir, "models", script_name)
    os.makedirs(model_dir, exist_ok=True)

    image_size = (256, 256)
    transforms_ = transforms.Compose([
        transforms.Resize(image_size),
        transforms.ToTensor(),
        transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))
    ])

    batch_size = 5

    trainloader = DataLoader(
        ImageDataset(data_dir, mode='train', transforms=transforms_),
        batch_size = batch_size,
        shuffle = True
    )

    validloader = DataLoader(
        ImageDataset(data_dir, mode='valid', transforms=transforms_),
        batch_size = batch_size,
        shuffle = False
    )
    Tensor = torch.cuda.FloatTensor if cuda else torch.Tensor
    n_epoches = 100

    for epoch in range(n_epoches):
        for i, (real_A, real_B) in enumerate(trainloader):
            real_A, real_B = real_A.type(Tensor), real_B.type(Tensor)

            # groud truth
            pred_real_A = D_A(real_A)
            valid_A = torch.ones_like(pred_real_A)
            fake_A = torch.zeros_like(pred_real_A)
            pred_real_B = D_B(real_B)
            valid_B = torch.ones_like(pred_real_B)
            fake_B = torch.zeros_like(pred_real_B)

            """Train Generators"""
            # set to training mode in the begining, because sample_images will set it to eval mode
            G_AB.train()
            G_BA.train()

            optimizer_G.zero_grad()

            fake_B_img = G_AB(real_A)
            fake_A_img = G_BA(real_B)

            # identity loss
            loss_id_A = criterion_identity(fake_B_img, real_A)
            loss_id_B = criterion_identity(fake_A_img, real_B)
            loss_identity = (loss_id_A + loss_id_B) / 2

            # GAN loss, train G to make D think it's true
            loss_GAN_AB = criterion_GAN(D_B(fake_B_img), valid_B)
            loss_GAN_BA = criterion_GAN(D_A(fake_A_img), valid_A)
            loss_GAN = (loss_GAN_AB + loss_GAN_BA) / 2

            # cycle loss
            recov_A = G_BA(fake_B_img)
            recov_B = G_AB(fake_A_img)
            loss_cycle_A = criterion_cycle(recov_A, real_A)
            loss_cycle_B = criterion_cycle(recov_B, real_B)
            loss_cycle = (loss_cycle_A + loss_cycle_B) / 2

            # G totol loss
            weight1 = 5
            weight2 = 1
            weight3 = 10
            loss_G = weight1*loss_identity + weight2*loss_GAN + weight3*loss_cycle

            loss_G.backward()
            optimizer_G.step()

            """Train Discriminator A"""
            optimizer_D_A.zero_grad()

            loss_real = criterion_GAN(pred_real_A, valid_A)
            loss_fake = criterion_GAN(D_A(fake_A_img.detach()), fake_A)
            loss_D_A = (loss_real + loss_fake) / 2

            loss_D_A.backward()
            optimizer_D_A.step()

            """Train Discriminator B"""
            optimizer_D_B.zero_grad()

            loss_real = criterion_GAN(pred_real_B, valid_B)
            loss_fake = criterion_GAN(D_B(fake_B_img.detach()), fake_B)
            loss_D_B = (loss_real + loss_fake) / 2

            loss_D_B.backward()
            optimizer_D_B.step()

        # validation
        if (epoch+1) % 10 == 0:
            valid_real_A, valid_real_B = next(iter(validloader))
            # sample_images(valid_real_A, valid_real_B)

            loss_D = (loss_D_A + loss_D_B) / 2
            print(f'[Epoch {epoch+1}/{n_epoches}]')
            print(f'[G loss: {loss_G.item()} | identity: {loss_identity.item()} GAN: {loss_GAN.item()} cycle: {loss_cycle.item()}]')
            print(f'[D loss: {loss_D.item()} | D_A: {loss_D_A.item()} D_B: {loss_D_B.item()}]')

    """## 5. Evaluation"""

    """
    Step 8. Generate Images
    """
    ## Translation 1: A Image --> B Image
    test_dir = os.path.join(data_dir, 'VAE_generation/test') # modification forbidden
    files = [os.path.join(test_dir, name) for name in os.listdir(test_dir)]

    save_dir = os.path.join(model_dir, 'generated_B_images')
    if not os.path.exists(save_dir):
        os.makedirs(save_dir)

    to_image = transforms.ToPILImage()

    G_AB.eval()
    for i in range(0, len(files), batch_size):
        # read images
        imgs = []
        for j in range(i, min(len(files), i+batch_size)):
            img = Image.open(files[j])
            img = transforms_(img)
            imgs.append(img)
        imgs = torch.stack(imgs, 0).type(Tensor)

        # generate
        fake_imgs = G_AB(imgs).detach().cpu()

        # save
        for j in range(fake_imgs.size(0)):
            img = fake_imgs[j].squeeze().permute(1, 2, 0)
            img_arr = img.numpy()
            img_arr = np.clip((img_arr + 1.0) * 127.5, 0, 255).astype(np.uint8)

            img = to_image(img_arr)
            _, name = os.path.split(files[i+j])
            img.save(os.path.join(save_dir, name))

    gt_dir = os.path.join(data_dir, 'VAE_generation1/test')
    metrics = torch_fidelity.calculate_metrics(
        input1=save_dir,
        input2=gt_dir,
        cuda=True,
        fid=True,
        isc=True
    )

    fid_score = metrics["frechet_inception_distance"]
    is_score = metrics["inception_score_mean"]

    if is_score > 0:
        s_value_1 = np.sqrt(fid_score / is_score)
        print("Geometric Mean Score:", s_value_1)
    else:
        print("IS is 0, GMS cannot be computed!")

    ## Translation 2: B Image --> A Image
    test_dir = os.path.join(data_dir, 'VAE_generation1/test') # modification forbidden
    files = [os.path.join(test_dir, name) for name in os.listdir(test_dir)]

    save_dir = os.path.join(model_dir, 'generated_A_images')
    if not os.path.exists(save_dir):
        os.makedirs(save_dir)

    G_BA.eval()
    for i in range(0, len(files), batch_size):
        # read images
        imgs = []
        for j in range(i, min(len(files), i+batch_size)):
            img = Image.open(files[j])
            img = transforms_(img)
            imgs.append(img)
        imgs = torch.stack(imgs, 0).type(Tensor)

        # generate
        fake_imgs = G_BA(imgs).detach().cpu()

        # save
        for j in range(fake_imgs.size(0)):
            img = fake_imgs[j].squeeze().permute(1, 2, 0)
            img_arr = img.numpy()
            img_arr = np.clip((img_arr + 1.0) * 127.5, 0, 255).astype(np.uint8)

            img = to_image(img_arr)
            _, name = os.path.split(files[i+j])
            img.save(os.path.join(save_dir, name))

    gt_dir = os.path.join(data_dir, 'VAE_generation/test')

    metrics = torch_fidelity.calculate_metrics(
        input1 = save_dir,
        input2 = gt_dir,
        cuda = True,
        fid = True,
        isc = True
    )

    fid_score = metrics["frechet_inception_distance"]
    is_score = metrics["inception_score_mean"]

    if is_score > 0:
        s_value_2 = np.sqrt(fid_score / is_score)
        print("Geometric Mean Score:", s_value_2)
    else:
        print("IS is 0, GMS cannot be computed!")

    # Save both GMS_B and GMS_A in the CSV
    s_value_1 = np.round(s_value_1, 5)
    s_value_2 = np.round(s_value_2, 5)
    df = pd.DataFrame({'id': [1], 'GMS_B': [s_value_1], 'GMS_A': [s_value_2]})
    csv_path = os.path.join(model_dir, "Userid.csv")
    df.to_csv(csv_path, index=False)

    print(f"CSV with GMS_B and GMS_A saved to {csv_path}")

if __name__ == "__main__":
    main()
